package combase.example.norgan.basedatosremota01.interfaces;

import android.net.nsd.NsdManager;

import combase.example.norgan.basedatosremota01.fragments.BienvenidaFragment;
import combase.example.norgan.basedatosremota01.fragments.ConsultarListaUsuarioImagenFragment;
import combase.example.norgan.basedatosremota01.fragments.ConsultarListaUsuariosFragment;
import combase.example.norgan.basedatosremota01.fragments.ConsultarUsuarioFragment;
import combase.example.norgan.basedatosremota01.fragments.DesarrolladorFragment;
import combase.example.norgan.basedatosremota01.fragments.RegistrarUsuarioFragment;

public interface IFragments extends BienvenidaFragment.OnFragmentInteractionListener,ConsultarListaUsuariosFragment.OnFragmentInteractionListener,ConsultarUsuarioFragment.OnFragmentInteractionListener,DesarrolladorFragment.OnFragmentInteractionListener,RegistrarUsuarioFragment.OnFragmentInteractionListener,ConsultarListaUsuarioImagenFragment.OnFragmentInteractionListener{





}
